version: '3'
services:
  mongo:
    image: mongo
    container_name: jguwekamongo
    restart: unless-stopped
    networks:
      - back-tier
  jguweka:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    links:
      - "mongo:mongodb"
    ports:
      - 8080
    depends_on:
      - mongo
    networks:
      - front-tier
      - back-tier
    labels:
      - "service-name:jguweka"
      - "service-type:app-srv"
      - "environment:monitoring"
  prometheus:
    image: prom/container-exporter
    container_name: jguwekaprometheus
    ports:
      - "9104:9104"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/cgroup
  lb:
    image: dockercloud/haproxy
    ports:
      - 80:80
    links:
      - jguweka
    networks:
      - front-tier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge